version: "3.8"

services:
  # 1. MLflow Tracking Server
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_tracking_server
    ports:
      - "5001:5000"
    volumes:
      - ./mlartifacts:/mlartifacts
      - ./mlflow_db:/mlflow/db
    entrypoint: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow/db/mlflow.db 
      --host 0.0.0.0 
      --port 5000
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: unless-stopped

  # 2. FastAPI Model Serving Server
  fastapi_serving:
    build:
      context: ./model_serve
      dockerfile: Dockerfile
    container_name: fastapi_model_server
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: unless-stopped
